#
#  This makefile is made for stm32f103 using HAL driver based autogenerated at 
# mbed online compiler.
#  based platform is [NUCLEO stm32f103]. 
#  if you rebuild, you should add '-j' option, it makes faster.(to enable 
# Parallel compilation)
# 

GCC_BIN = 
PROJECT = LED_Blink

#use debugger?
DEBUG = 0

DRIVERSDIR = ./Drivers
HALDIR = $(DRIVERSDIR)/STM32F1xx_HAL_Driver
CMSISDIR = $(DRIVERSDIR)/CMSIS
CMSIS_DEVICEDIR = $(CMSISDIR)/Device/ST/STM32F1xx
MIDDLE_DRIVERDIR = $(DRIVERSDIR)/middleLayers

OBJDIR=./obj

USR_SRCDIR = ./Src
HAL_SRCDIR = $(HALDIR)/Src
MIDDLE_SRCDIRS = $(dir $(wildcard $(MIDDLE_DRIVERDIR)/*/))Src
STARTUP_SRC = $(DRIVERSDIR)/startup_stm32f103xe.s
STARTUP_OBJ = startup.o

BINDIR = ./bin

SOURCES   = 	\
		$(wildcard $(USR_SRCDIR)/*.c)	\
		$(wildcard $(HAL_SRCDIR)/*.c)	\
		$(wildcard $(MIDDLE_SRCDIRS)/*.c)

SYS_OBJECTS = 	$(addprefix $(OBJDIR)/, $(notdir $(SOURCES:.c=.o)))\
		$(OBJDIR)/$(STARTUP_OBJ)

INCLUDEDIRS = -I./Inc							\
		-I$(HALDIR)/Inc						\
		-I $(CMSISDIR)/Inc					\
		-I $(CMSIS_DEVICEDIR)/Inc				\
		$(addprefix -I, $(wildcard $(MIDDLE_DRIVERDIR)/*/Inc))

LINKER_SCRIPT = $(DRIVERSDIR)/STM32F103VETx_FLASH.ld

CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE    = $(GCC_BIN)arm-none-eabi-size 

CPU = -mcpu=cortex-m3 -mthumb 

CC_FLAGS = $(CPU) -c -fno-common -fmessage-length=0 -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -MMD -MP

CC_SYMBOLS = -DTARGET_FF_ARDUINO -DTARGET_NUCLEO_F103RB -DTOOLCHAIN_GCC -DTARGET_FF_MORPHO -DTARGET_LIKE_CORTEX_M3 -DTARGET_CORTEX_M -DTARGET_LIKE_MBED -DTARGET_STM32F1 -D__MBED__=1 -DARM_MATH_CM3 -DMBED_BUILD_TIMESTAMP=1463831794.11 -DTARGET_STM -DTOOLCHAIN_GCC_ARM -D__CORTEX_M3 -DTARGET_M3 -DTARGET_STM32F103RB 

LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float -Wl,-Map=$(BINDIR)/$(PROJECT).map,-cref
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -Og -g3
else
  CC_FLAGS += -DNDEBUG -Os -g0
endif

.PHONY: all clean lst size disp openocd

all: $(BINDIR)/$(PROJECT).bin $(BINDIR)/$(PROJECT).hex size

clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJDIR) $(BINDIR) -rf

$(OBJDIR)/$(STARTUP_OBJ): $(STARTUP_SRC)
	$(CC) $(CPU) -c -x assembler-with-cpp -o $@ $<

$(OBJDIR)/%.o: $(HAL_SRCDIR)/%.c
	-mkdir -p $(OBJDIR)
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDEDIRS) -o $@ $<

$(OBJDIR)/%.o: $(USR_SRCDIR)/%.c
	-mkdir -p $(OBJDIR)
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDEDIRS) -o $@ $<

$(OBJDIR)/%.o: $(MIDDLE_SRCDIRS)/%.c
	-mkdir -p $(OBJDIR)
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDEDIRS) -o $@ $<

$(BINDIR)/$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	-mkdir -p $(BINDIR)
	$(LD) $(LD_FLAGS) -T $(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ -Wl,--start-group $(LIBRARIES) $(LD_SYS_LIBS) -Wl,--end-group

$(BINDIR)/$(PROJECT).bin: $(BINDIR)/$(PROJECT).elf
	$(OBJCOPY) -O binary $< $@

$(BINDIR)/$(PROJECT).hex: $(BINDIR)/$(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(BINDIR)/$(PROJECT).lst: $(BINDIR)/$(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size: $(BINDIR)/$(PROJECT).elf
	$(SIZE) $(BINDIR)/$(PROJECT).elf
#	echo $(MIDDLE_SRCDIRS)

OPENOCDPATH=~/Workspace/program/0.10.0-201601101000-dev/bin
OPENOCDCONFIGDIR=./Drivers/openocd_configulation

openocd: $(BINDIR)/$(PROJECT).elf
	$(OPENOCDPATH)/openocd -f $(OPENOCDCONFIGDIR)/stlink-v2-1.cfg -f $(OPENOCDCONFIGDIR)/stm32f1x_flash.cfg


DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
